### ISSUE TITLE
Non-game data for demo

### ISSUE THREAD

**Issue by jinokian** [kissmygritts/proto-dashboard#35]
Include an example(s) of non-game species data in the cards on the homepage and if possible as an encounter with activities on the encounter page.

**Comment by kissmygritts** [comment]
This is a duplicate: https://github.com/kissmygritts/proto-dashboard/issues/15.

Closing

**Comment by kissmygritts** [comment]
Nevermind...

**Comment by kissmygritts** [comment]
I've added more data. For future reference an issue like this should be added to the gus database repo, not the frontend repo.
